### ISSUE TITLE
Trilateration in a 3D space

### ISSUE THREAD

**Issue by Alex-Beh** [jonathanrjpereira/UWB#1]
Thanks for the good documentation and code. May I know does this repo support trilateration in a 3D space? From my knowledge, just change the circle equation in a sphere equation.

In my project, I would like to mount the anchors on a moving robot and track the person who holding the tag in front of the robot. The moving tag is outside of the enclosure of the 4 fixed anchors on the robot. However, the raw distance of tag to anchor that I get from bluetooth api is quite noise. May I know how would you suggest for my setup?

**Comment by jonathanrjpereira** [comment]
Right now, the code is limited to 2D space. But in the future, almost every simulation/hardware implementation will be updated to work in a 3D space.

I would perform the following debugging steps:

- Individually test each module for distance measurements and ensure they are properly calibrated.
- UWB modules don't work well near metallic objects. So make sure the module is not mounted near a metallic object (on the robot).
- Ensure all modules are powered correctly. 
- Once you have completed the above steps, test if you can track/trilaterate an object with just 3 anchors. Only then, test trilateration with more anchors. Once this is successful mount them on the robot.

**Comment by Alex-Beh** [comment]
Currently I am trying the configuration which shown in this research paper ([link](https://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=8419698)). May I know how can I do the calibration to the anchors? I didn't find the related documentation....

**Comment by jonathanrjpereira** [comment]
In the [research paper](https://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=8419698),  the anchors are mounted at fixed points on the robot i.e the anchors are placed at known locations (the distance between each anchor is known and the locations are also known). Hence in order to find the position of the tag, you just need to plug in these known values into the hyperbolic positioning algorithm. Hence there is no need for any **Self-Calibrating Anchor Scheme** which [this repository](https://github.com/jonathanrjpereira/UWB) focuses on.

When it comes to anchor distance measurement calibration, the paper uses the following method: 

> The distance data from the anchors and the tag are obtained. The actual distances are also measured by a ruler, and the data from UWB anchors are calibrated according to the actual distances measured by the ruler. This is a rather inefficient way of calibrating the UWB modules. 

Decawave recommends the calibration algorithm in[ ANTENNA DELAY CALIBRATION OF DW1000-BASED PRODUCTS AND SYSTEMS](decawave.com/wp-content/uploads/2018/10/APS014_Antennna-Delay-Calibration_V1.2.pdf).  I'm currently working on a script for this. It should be ready in the next couple of weeks.
